# ---------------------------------------------------------------------------
# LIBRERIAN THEME MANAGER
# ------------------------
# This file can be edited to safely change Librarian theme. Edit the values
# below.
# This system is placeholder for future, more complex theme manager, allowing
# to use various themes and switching between them within the software.
# ---------------------------------------------------------------------------

[Titlebar]
text_colour       = "#b2c2ac" #| b2c2ac
background_colour = "#632985" #| 632985