# ---------------------------------------------------------------------------
# LANGUAGE FILE
# ------------------------
# Language files are meant to support multilingualistic experience for
# Librerian. They can have any name supported by Librerian natively, or
# any name ever, if you edit 'settings.toml' manually.
#
# Keys in this file are used for user interface, so be sure to not remove
# any of them.
# ---------------------------------------------------------------------------
# CONTRIBUTORS
# - CrashGyuluka

#| Translators in key below should replace "English" with their respective
#| language, and translate it (so, Polish would have "Polski" there)
current__language = "Hungarian"

login__choose_account = "Válaszd ki a fiókodat"
login__enter = "Belépés"
login__add = "Új fiók hozzáadása"
login__new_account = "Add meg a fiókod nevét"
login__confirm = "Megerősítés"

menu__settings = "Settings"
menu__donate = "Donate the Author"
menu__exit = "Exit"

settings__languages = "Change language"
settings__themes = "Change theme"
settings__confirm = "Megerősítés"
settings__lang = "Choose language"
settings__theme = "Choose theme"

entry__book = "Könyvek"